general.import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
general.live_config_reload = true

window.title = "Terminal"
window.opacity = 1
window.blur = false 

font.normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
font.size = 15.0

cursor.style = { shape = "Beam", blinking =  "On" }
